### ISSUE TITLE
searchcriterias always empty

### ISSUE THREAD

**Issue by cfreak** [onOfficeGmbH/sdk#65]
Wir versuchen derzeit über die API die Suchkriterien einer Adresse auszulesen. z.B. der Adresse mit der Internal ID:; 119. 

Dazu benutzen wir das onOffice SDK und folgenden Code:

```php
$parameters = [
    "mode" => "internal",
    'ids' => [119],
];
$handleRead = $this->pSDK->callGeneric(onOfficeSDK::ACTION_ID_GET, 'searchcriterias', $parameters);

$this->pSDK->sendRequests($this->token, $this->secret);
return $this->pSDK->getResponseArray($handleRead);
```

Die Response lautet aber jedes mal:

array:7 [ // app/Console/Commands/OnOffice/syncCustomersFromOnOffice.php:165
  "actionid" => "urn:onoffice-de-ns:smart:2.5:smartml:action:get"
  "resourceid" => ""
  "resourcetype" => "searchcriterias"
  "cacheable" => true
  "identifier" => ""
  "data" => array:2 [
    "meta" => array:1 [
      "cntabsolute" => null
    ]
    "records" => []
  ]
  "status" => array:2 [
    "errorcode" => 0
    "message" => "OK"
  ]
]

obwohl der Kunde definitiv ein Suchprofil angelegt hat.

Was machen wir falsch?

**Comment by jayay** [comment]
Hallo @cfreak,

haben Sie bereits geprüft, ob der API-User in enterprise die Leserechte für die entsprechenden Suchkriterien hat? Standardmäßig sind die Leserechte stark eingeschränkt.

**Comment by cfreak** [comment]
Das wars, vielen lieben dank
