### ISSUE TITLE
Roadmap to v1.0.0

### ISSUE THREAD

**Issue by legionth** [onOfficeGmbH/sdk#8]
This project is currently used in some other projects which are already in production.

We want to follow the release scheme of [Semantic Verisioning](https://semver.org/) for upcoming releases.
For the `v1.0.0` we will intodruce some backwards compatibility breaks in order to create a more fitting consumer expierence in the future. There is currently no intention for `v1.0.0` to change the communication with official onOffice API. The intention for this library is to ease the implementation into existing eco-systems.

I set up a roadmap that should adress all major changes for each past and upcoming versions:

# v0.1.0 ✅ 

* Released: 2020-02-12
* Adding this repository to [packagist](https://packagist.org/)
* Create general documentation
* Add composer.json 

# v0.2.0✅

* Released: 2020-02-24
* Use PSR-4 composer Autoloader
* Adding unit tests via PHPUnit
* Adding CI pipline to the repository

# v1.0.0

* Planned 2020?
* Introduce PSR-12
* Refactoring code for better consumer expierience
* Use PSR-7 Request Objects
* Adding static code analysis tool with PHPstan
* Adding code style analysis with CSFixer

This ticket aims to serve as a basic overview and does not contain every single change. Please also see the CHANGELOG for more details.

We try to update this continously.

**Please keep the discussions in this ticket to a minimum.**  So problems can be identified fast and discussed more focused.

Please open an [issue](https://github.com/onOfficeGmbH/sdk/issues) if you have further questions or recommandations.

**Comment by dkaisers** [comment]
That's a good start I think. I would like to add the renaming of the main folder from *SDK* to *src* and correcting the casing of the main class in accordance with PSR-12 to the list.

**Comment by legionth** [comment]
Add a `v0.2.0` in between, to create a better experience to add this library. These changes are BC, but according to [semver](https://semver.org/#spec-item-4) we are still on the major version `v0.x.y` which can contain BC.

**Comment by dkaisers** [comment]
We should also probably define a PHP version requirement in the composer.json. I think currently the SDK aims to work against PHP 7 and above.

**Comment by legionth** [comment]
Since this list confuses some people, we'll close this issue for now.

`v0.2.0` is already used in several productive system there is currently no need for breaking changes in the near future.

**Comment by mpfeifer-onOffice** [comment]
I'd like to pick this up again but without using PSR-7, without BC-breaking changes. Just to get the SDK up to 2026 standards.
